version: '3.9'

services:
  app:
    image: exchange:latest
    depends_on:
      postgres-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-server:5432/exchange
      SPRING_DATASOURCE_USERNAME: exchange
      SPRING_DATASOURCE_PASSWORD: exchange_password
    ports:
      - "8081:8080"

  postgres-server:
    image: postgres
    restart: always
    shm_size: 1Gb
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/
      - exchange_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U default" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  exchange_pgdata:
